### ISSUE TITLE
hi, I have a problem in operate the bash commend

### ISSUE THREAD

**Issue by jzw0707** [Suhyun777/CVPR23-GAP#1]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=16V_ZlkW4SsnNDtnGmaBRq2OoPmUOc5mY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001879D6DEBB0>:
 Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

please help me to solve the problem, thank you!

**Comment by Suhyun777** [comment]
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=16V_ZlkW4SsnNDtnGmaBRq2OoPmUOc5mY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001879D6DEBB0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
> 
> please help me to solve the problem, thank you!

Hi, thanks for your interest in my work!
I think it's because of torchmeta's dataset code file. I recommend that you use **my dataset code file** rather than the code file in torchmeta. If you have problems using my dataset code file, please post an additional issue.
